apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-affinity-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpu-affinity-scheduler
rules:
- apiGroups: [""] # Core API group
  resources:
    - pods
    - pods/binding
    - nodes
    - bindings
    - events
    - namespaces
    - persistentvolumeclaims
    - persistentvolumes
    - replicationcontrollers
    - configmaps
    - endpoints
    - services
    - secrets
    - serviceaccounts
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups: ["apps"] # Apps API group
  resources:
    - replicasets
    - statefulsets
    - daemonsets
    - deployments
  verbs:
    - get
    - list
    - watch
- apiGroups: ["storage.k8s.io"] # Storage API group
  resources:
    - csidrivers
    - csinodes
    - csistoragecapacities
    - storageclasses
    - volumeattachments
  verbs:
    - get
    - list
    - watch
- apiGroups: ["policy"] # Policy API group
  resources:
    - poddisruptionbudgets
  verbs:
    - get
    - list
    - watch
- apiGroups: ["events.k8s.io"] # Events API group
  resources:
    - events
  verbs:
    - create
    - patch
    - update
- apiGroups: ["scheduling.k8s.io"] # Scheduling API group
  resources:
    - priorityclasses
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpu-affinity-scheduler
subjects:
- kind: ServiceAccount
  name: cpu-affinity-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cpu-affinity-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-affinity-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-affinity-scheduler
  template:
    metadata:
      labels:
        app: cpu-affinity-scheduler
    spec:
      serviceAccountName: cpu-affinity-scheduler
      containers:
      - name: scheduler
        image: intel-112:5000/my-cpu-affinity-scheduler-plugin:amd64
        imagePullPolicy: IfNotPresent
        args:
        - --config=/etc/kubernetes/scheduler-config.yaml
        - --v=4
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: cpu-affinity-scheduler
        plugins:
          score:
            enabled:
              - name: NodeResourcesFit
              - name: NodeResourcesBalancedAllocation
              #- name: CPUAffinityPlugin
        pluginConfig:
          - name: NodeResourcesFit
            args:
              scoringStrategy:
                type: MostAllocated
                resources:
                  - name: cpu
                    weight: 1
                  - name: memory
                    weight: 1
          # - name: CPUAffinityPlugin
          #   args:
          #     highPriorityScore: 10000
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: green-serverless
  labels:
    app: my-scheduler-test-pod
spec:
  schedulerName: cpu-affinity-scheduler  
  containers:
  - name: test
    image: intel-112:5000/nginx